# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7818a8705fa68618673945ab3e4af057a2a20f94ef52d2b3e231350a4ae8acf5d5b44b88537abcee4eba9c5e5256c0135042318b737486dd9312e7e1142abaca

test:
  secret_key_base: 2fe0e5b9d88890029a9c5794ae69a98ff4ea2b65bc64e7e84cec85e134a2990013c5f4d79e72d9bf352ee4f5638bad06b3e6bcbc57879441d6bf7b73274981ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
